query GetOrders(
    $customerAccessToken: String!
) {
    customer(customerAccessToken: $customerAccessToken) {
        id

        orders(first: 20, reverse: true) {
            nodes {
                id
                orderNumber
                processedAt
                financialStatus
                fulfillmentStatus
                
                currentTotalPrice {
                    amount
                    currencyCode
                }

                lineItems(first: 250) {
                    nodes {
                        quantity
                        variant {
                            image {
                                url
                            }
                        }
                    }
                }
            }
        }
    }
}