package com.troves.designsystem.theme

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

data class ColorScheme(
    val primary: Color,
    val primaryVariant: Color,
    val onPrimary: Color,
    val secondary: Color,
    val onSecondary: Color,
    val backGround: Color,
    val primaryFont: Color,
    val secondaryFont: Color,
    val surface: Color,
    val surfaceVariant: Color,
    val onSurface: Color,
    val hint: Color,
    val warning: Color,
    val onWarning: Color,
    val error: Color,
    val onError: Color,
    val success: Color,
    val onSuccess: Color,
    val amber: Color,
    val onAmber: Color,
    val disable: Color,
    val onDisable: Color,
)
val lightColors = ColorScheme(
    primary = Color(0xFFA9B6A1),
    primaryVariant = Color(0xFF8E9B87),
    secondary = Color(0xFFD2D9CC),
    backGround = Color(0xFFFCF9F6),
    primaryFont = Color(0xFF000000),
    secondaryFont = Color(0xFF636369),
    surface = Color(0xFFF4F2ED),
    surfaceVariant = Color(0xFFF9F7FC),
    hint = Color(0xFFA7A7A7),
    warning = Color(0xFFFFC107),
    error = Color(0xFFF44336),
    success = Color(0xFF4CAF50),
    amber = Color(0xFFD97706),
    onAmber = Color(0xFFFFFFFF),
    onSurface = Color(0xFF000000),
    disable = Color(0xF1FAFAFA),
    onDisable = Color(0xFFBDBDBD),
    onPrimary = Color(0xFFFFFFFF),
    onSecondary = Color(0xFFFFFFFF),
    onWarning = Color(0xFF000000),
    onError = Color(0xFFFFFFFF),
    onSuccess = Color(0xFFFFFFFF),
)

val darkColors = ColorScheme(
    primary = Color(0xFFA9B6A1),
    primaryVariant = Color(0xFF8E9B87),
    secondary = Color(0xFF7CB3C0),
    backGround = Color(0xFF121212),
    primaryFont = Color(0xFFEEEEEE),
    secondaryFont = Color(0xFFAAAAAA),
    surface = Color(0xFF1E1E1E),
    surfaceVariant = Color(0xFF1C1A22),
    hint = Color(0xFF757575),
    warning = Color(0xFFFFD54F),
    error = Color(0xFFCF6679),
    success = Color(0xFF81C784),
    amber = Color(0xFFD97706),
    onAmber = Color(0xFFFFFFFF),
    disable = Color(0xFF333333),
    onSurface = Color(0xFFEEEEEE),
    onDisable = Color(0xFF555555),
    onPrimary = Color(0xFF121212),
    onSecondary = Color(0xFF121212),
    onWarning = Color(0xFF121212),
    onError = Color(0xFF121212),
    onSuccess = Color(0xFF121212),
)

internal val localSPColorScheme = staticCompositionLocalOf { darkColors }